export const ProductAction_types={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED-PRODUCTS",
    REMOVE_SELECTED_PRODUCTS:"REMOVE_SELECTED_PRODUCTS",
    ADD_TO_CART:"ADDTOCART",
    REMOVE_TO_CART:"REMOVETOCART"
}